{% set version = "1.9.1" %}

package:
  name: basictools
  version: {{ version }}

source:
  url: https://gitlab.com/DRTI/basic-tools/-/archive/{{ version }}/basic-tools-{{ version }}.tar.bz2
  sha256: 3ea5f1bd192a1772bc20d92b8b85f6d4fa0ca278fd60ae0871618cd2aed570e5

build:
  number: 0
  script_env:
    - CC=${CXX}  # [unix]
    - EIGEN_INC=${PREFIX}/include/eigen3  # [unix]
    - set EIGEN_INC=%LIBRARY_INC%\eigen3  # [win]
    - BASICTOOLS_DISABLE_MKL=1
    - BASICTOOLS_DISABLE_OPENMP=1
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  entry_points:
    - "MeshFileConvert = BasicTools.IO.MeshFileConverter:Main"

  skip_compile_pyc:
    "BasicToolsParaViewBridge.py"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python  {{ python }}
    - numpy >=1.20
    - pip
    - cython
    - eigency
    - mkl
    - mkl-include
    - eigen
    - sympy
    - setuptools-scm
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - psutil
    - pywin32  # [win]
    - pyparsing
    - scipy >=1.9
    - scikit-sparse  # [not win]
    - pyamg
    - sympy
    - h5py
    - mpi4py  # [not win]
    - vtk
    - matplotlib-base
    - eigency
    - mkl
    - pycgns
    - networkx >=3.0  # [not win]
    - meshio
    - pyvista
    - scikit-learn


test:
  requires:
    - OpenSSH  # [linux]
    - mesalib >=21.0  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
  imports:
    - BasicTools
  commands :
    - python -u -m BasicTools.Helpers.Tests -k Catalyst -k OpenInParaView -k PyVistaBridge -f  -s  # [not win]
    - python -u -m BasicTools.Helpers.Tests -k Catalyst -k UnstructuredMeshGraphTools -k UtSplitter -k UtMerger -f -s  # [win]

about:
  home: https://gitlab.com/DRTI/basic-tools
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Tools for finite element computations

extra:
  recipe-maintainers:
    - fbordeu
