{% set version = "2.0.0rc0" %}

package:
  name: muscat
  version: {{ version }}


source:
  url: https://gitlab.com/drti/muscat/-/archive/{{ version }}/muscat-{{ version }}.tar.bz2
  sha256: 5dd7a32d10968c5acfedafd9b6c2d274e1f8d808c45435d1b748019170fe5b9d


build:
  number: 1
  skip: True  # [py==38 and osx]

outputs:
  - name: muscat-core
    version: {{ version }}
    script: build_core.sh  # [not win]
    script: bld_core.bat  # [win]
    build:
      entry_points:
        - "MeshFileConvert = Muscat.IO.MeshFileConverter:Main"
      skip_compile_pyc:
        "MuscatParaViewPlugin.py"

    requirements:
      build:
        - python
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cython <3
      host:
        - python
        - numpy =1.21  # [py==38]
        - numpy =1.21  # [py==39]
        - numpy =1.21  # [py==310]
        - numpy =1.23.4  # [py==311]
        - cython <3
        - sympy
        - eigency
        - mkl
        - mkl-include
        - setuptools-scm
        - eigen
        - boost-cpp
        - pip
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy >=1.9
        - sympy
        - eigency
        - mkl
        - networkx >=3.0
        - scikit-sparse
    test:
      imports:
        - Muscat
      commands:
        - python -u -m Muscat.Helpers.Check

  - name: "muscat-extensions"
    version: {{ version }}
    requirements:
      host:
        - python
        - numpy =1.21  # [py==38]
        - numpy =1.21  # [py==39]
        - numpy =1.21  # [py==310]
        - numpy =1.23  # [py==311]
        - vtk
        - psutil
        - scikit-sparse
        - h5py
        - meshio
        - pyvista
        - networkx >=3.0
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - vtk
        - psutil
        - scikit-sparse
        - h5py
        - meshio
        - pyvista
        - networkx >=3.0
    test:
      imports:
        - psutil
        - sksparse.cholmod
        - h5py
        - meshio
        - networkx

  - name: "muscat"
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage('muscat-core', exact=True) }}
        - {{ pin_subpackage('muscat-extensions', exact=True) }}
    test:
      imports:
        - Muscat
      commands:
        - python -u -m Muscat.Helpers.Check

  - name: "muscat-devenv"
    version: {{ version }}
    requirements:
      - {{ compiler('cxx') }}
      - python
      - {{ pin_compatible('numpy') }}
      - sympy
      - cython <3
      - eigency
      - mkl
      - mkl-include
      - setuptools-scm
      - eigen
      - scipy >=1.9
      - eigency
      - scikit-sparse
      - h5py
      - pycgns
      - networkx >=3.0
      - boost-cpp
      - pytest
      - vtk
    test:
      imports:
        - numpy

about:
  home: https://gitlab.com/drti/muscat
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Tools for finite element computations

extra:
  recipe-maintainers:
    - fbordeu
