{% set version = "1.5" %}

package:
  name: basictools
  version: {{ version }}

source:
  url: https://gitlab.com/DRTI/basic-tools/-/archive/v{{ version }}/basic-tools-v{{ version }}.tar.bz2
  sha256: 6a51099667287fce53e1def5c4128cd7652535f9ac264153476ffd22111d31fa

build:
  number: 1
  script: CC=${CXX} EIGEN_INC=${PREFIX}/include/eigen3 BASICTOOLS_DISABLE_MKL=1 BASICTOOLS_DISABLE_OPENMP=1 ${PYTHON} -m pip install --no-deps . -vv  # [unix]
  script: set EIGEN_INC=%LIBRARY_INC%\eigen3 & set BASICTOOLS_DISABLE_MKL=1 & BASICTOOLS_DISABLE_OPENMP=1 & %PYTHON% -m pip install --no-deps . -vv  # [win]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - eigen
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - scikit-sparse  # [not win]
    - pyamg
    - sympy
    - h5py
    - pyparsing
    - mpi4py  # [not win]
    - vtk
    - matplotlib-base

test:
  imports:
    - BasicTools

about:
  home: https://gitlab.com/DRTI/basic-tools
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Safran FE helper tools

extra:
  recipe-maintainers:
    - jschueller
