{% set version = "1.3" %}

package:
  name: basictools
  version: {{ version }}

source:
  url: https://gitlab.com/DRTI/basic-tools/-/archive/v{{ version }}/basic-tools-v{{ version }}.tar.bz2
  sha256: 192f0930b47e0500a7770d712586caf8575d3792e22ed71b498bb698f5bd3128
  patches:
    # disable mkl, openmp
    - setup.patch

build:
  number: 0
  script: CC=${CXX} EIGEN_INC=${PREFIX}/include/eigen3 ${PYTHON} -m pip install --no-deps . -vv  # [unix]
  script: set EIGEN_INC=%LIBRARY_INC%\eigen3 & %PYTHON% -m pip install --no-deps . -vv  # [win]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - eigen
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - scikit-sparse  # [not win]
    - pyamg
    - sympy
    - h5py
    - pyparsing
    - mpi4py  # [not win]
    - vtk
    - matplotlib-base

test:
  imports:
    - BasicTools

about:
  home: https://gitlab.com/DRTI/basic-tools
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Safran FE helper tools

extra:
  recipe-maintainers:
    - jschueller
